camera:
  num_poses: 1
  camera_intrinsics: [[615.95776367187, 0.0, 320], [0.0, 615.95776367187, 240], [0.0, 0.0, 1.0]]

rest_surface:
  type: bin
  surface_pose: [0.225, -0.15, 0, 0.707, 0.707, 0, 0]

Models: [dove]

params:
  num_images: 1
  # options: obj/ply, default: ply
  object_model_type: obj
  # options: pixel, box
  label_type: pixel
  # options: cycles, blender, flat
  renderer: blender
  min_distance: 0.02
  save_debug: True
  num_object_instances: 9
  minimum_objects_in_scene: 5
  maximum_objects_in_scene: 10
  # pose range
  range_x: [0.25, 0.54]
  range_y: [-0.25, -0.45]
  range_z: [-0.09, 0]
  range_euler_x: [0, 360]
  range_euler_y: [0, 360]
  range_euler_z: [0, 360]
  num_simulation_steps: 20
  light_position_range_x: [0.38, 0.45]
  light_position_range_y: [-0.32, -0.36]
  light_position_range_z: [0.1, 0.4]
